name: LightRTP
version: '${version}'
main: com.nextdevv.lightrtp.LightRTP
api-version: '1.17'
commands:
    rtp:
        description: LightRTP command
        usage: /<command>
        aliases: [randomtp]
        permission: lightrtp.rtp
    rtpnear:
        description: LightRTP command
        usage: /<command>
        aliases: [rtpn]
        permission: lightrtp.rtpnear
    rtpcave:
        description: LightRTP command
        usage: /<command>
        aliases: [rtpc]
        permission: lightrtp.rtpcave
    lightrtp:
        description: LightRTP command
        usage: /<command> <args>
        aliases: [lrtp]
        permission: lightrtp.admin


permissions:
    lightrtp.rtp:
        description: Allows the player to use the /rtp command
        default: true
    lightrtp.admin:
        description: Allows the player to use the /lightrtp command
        default: op
    lightrtp.rtpnear:
        description: Allows the player to use the /rtpnear command
        default: true
    lightRTP.rtpcave:
        description: Allows the player to use the /rtpcave command
        default: true